spring:
  profiles:
    active: dev
    #active后的参数代表启用哪个环境
    #笔记：在Spring Boot中多环境配置文件名需要满足application-{profile}.yml的格式，其中{profile}对应你的环境标识，比如：
    #application-dev.yml：开发环境
    #application-test.yml：测试环境
    #application-prod.yml：生产环境